import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import StyledComponentsRegistry from "@/lib/registry";
import nextFontLocal from 'next/font/local';
import { Press_Start_2P } from "next/font/google";

const consolas = nextFontLocal({
  src: '../public/fonts/Consolas.ttf',
  variable: '--font-consolas',
});
const pressStart = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-press-start",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  
});


export const metadata: Metadata = {
  title: "DriftSeeker",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${consolas.variable} ${pressStart.variable} antialiased overflow-x-hidden`}
      >
        
        <Providers>
          <StyledComponentsRegistry>
            <Navbar />
            {children}
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}
